#!/bin/bash

cd files

# the user id (uid) to send the notification to (with notify-send)
UID_NOTIFICATION="1000"

cp 99-simple-usb-automount.rules /etc/udev/rules.d/

if [[ "$1" == "ro" ]]; then
	sed 's/mntopts="/&ro,/' simple-usb-automount > /usr/local/bin/simple-usb-automount
else
	cp simple-usb-automount /usr/local/bin/
fi
chmod +x /usr/local/bin/simple-usb-automount

sed "s/{UID}/$UID_NOTIFICATION/; s/{USER}/$(getent passwd "$UID_NOTIFICATION" | cut -d: -f1)/" simple-usb-automount@.service > /etc/systemd/system/simple-usb-automount@.service

systemctl daemon-reload

udevadm control --reload-rules

echo "Done"

