#!/bin/bash

mnt="/usb/"
mntopts="nosuid,nodev,noexec"
dev="/dev/$2"

mkdir /usb -p
findmnt /usb || sudo mount -t tmpfs tmpfs /usb

if [[ "$1" == "a" ]]; then
	for part in $(lsblk -nro name "$dev" | tac)
	do
		mkdir "$mnt$part" -p
		mount "/dev/$part" "$mnt$part" -o "$mntopts"
		if [[ "$?" -eq 0 ]]; then
			sudo -u "$DISP_USER" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$DISP_UID/bus" notify-send "Mounted /dev/$part at $mnt$part"
		else
			rmdir "$mnt$part"
		fi
	done
else
	for part in $(ls "$mnt" | grep "^$2")
	do
		umount "$mnt$part"
		rmdir "$mnt$part"
	done
fi

